

services:
  # 1. Conteneur PHP (Backend Laravel)
  app:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: atelier_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ../Backend_Frontend:/var/www
      - atelier_vendor:/var/www/vendor
      - ./php/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
    networks:
      - atelier_network

  # 2. Serveur Web (Nginx)
  webserver:
    image: nginx:alpine
    container_name: atelier_webserver
    restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - ../Backend_Frontend:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - atelier_network

  # 3. Base de données (PostgreSQL)
  database:
    image: postgres:15-alpine
    container_name: atelier_db
    restart: unless-stopped
    ports:
      - "5436:5432"
    environment:
      POSTGRES_DB: gestion_atelier
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - atelier_network

  # 4. Conteneur Node.js (Compilation Vue.js / Vite)
  node:
    image: node:20-alpine
    profiles: ["dev"]
    container_name: atelier_node
    working_dir: /var/www
    volumes:
      - ../Backend_Frontend:/var/www
    ports:
      - "5174:5173"
    command: "npm run dev -- --host"
    networks:
      - atelier_network

networks:
  atelier_network:
    driver: bridge

volumes:
  db_data:
  atelier_vendor: