server {
    listen 80;
    index index.php index.html;
    server_name localhost;

    # On pointe vers le dossier "public" de Laravel
    root /var/www/public;

    # Redirection des URLs propres (très important pour Laravel)
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Configuration pour exécuter le code PHP via notre conteneur "app"
    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}